apiVersion: v1
kind: Pod
metadata:
  name: distance-calculator
  labels:
    app: distance-calculator
spec:
  containers:
  - name: distance-calculator
    image: distance-calculator1:v1.0.0
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true 