apiVersion: v1
kind: Pod
metadata:
  name: distance-calculator
  labels:
    app: distance-calculator
spec:
  containers:
  - name: distance-calculator
    image: distance-calculator1:v1.1.0
    imagePullPolicy: IfNotPresent
    envFrom:
    - configMapRef:
        name: distance-config
    stdin: true
    tty: true 