apiVersion: v1
kind: Service
metadata:
  name: distance-calculator-service
spec:
  selector:
    app: distance-calculator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 