apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  DB_HOST: "postgres-service.database"  # Формат: <имя-сервиса>.<namespace>
  DB_PORT: "5432"
  DB_NAME: "distancedb"
  FORMULA: "sqrt((x2-x1)^2 + (y2-y1)^2)" 