apiVersion: v1
kind: Secret
metadata:
  name: db-secret-credentials
  labels:
    app: my-database
data:
  POSTGRES_DB: ZGlzdGFuY2VkYg==  # distancedb в base64
  POSTGRES_USER: YWdhc3NoaQ==  # agasshi в base64
  POSTGRES_PASSWORD: MTM3OQ==  # 1379 в base64
   # P@ssw0rd